### ISSUE TITLE
Create a Player

### ISSUE THREAD

**Issue by Anedumgottil** [Anedumgottil/VR-Mazmorra#10]
- should represent player in VR
- give them health for now
- needs to be able to pick up items
	 - use unity steamvr tutorial to grab a grenade
		 - get grenade model
		 - deal with spawning in microblocks on a large scale
		 - microblocks destroy/fade after a period of time
- keep track of position, turret will fire at player

**Comment by apodgo2** [comment]
We're going to have to push the microblock generation and the Grenade thing back till next demo. MapGen took a hell of a lot more time than expected, as usual... so we're just going to allow the player to teleport using DPad and spawn MapBlocks with the other controller for now. no health or nothing.

**Comment by apodgo2** [comment]
Player exists 9993f01e96451d01ec1fb8ca34700295cbecacf8

**Comment by apodgo2** [comment]
Player teleportation via SteamVR Dpad press added d5a53d349954bdb08c8b409b23496a0194463781

One more commit to add world generation and I'll close it

**Comment by apodgo2** [comment]
Player teleportation via SteamVR Dpad press improved cb181b79e8be068a7f44d46b1998aa06f1a1bc9b

**Comment by apodgo2** [comment]
This is pretty much ready to go with the new VRTK scripts we just have to extend it.
