### ISSUE TITLE
Lower quality of rendered object.

### ISSUE THREAD

**Issue by slobanwala1** [Anedumgottil/VR-Mazmorra#6]
Rendered objects from blender are of high quality for small pieces when loading them together takes time to generate.

**Comment by apodgo2** [comment]
I moved the blender files out of the Unity object, importing them on every Unity launch was taking wayyy too much time

see commit 881ad12a6b20f7a27dce1bca5cfac6fbdc35efe7

they're stored in the root directory of the repo, once you decimate them and convert them into OBJ files please remove the blend files from the repository
